import java.io.*;
import java.util.Scanner;
public class FileLetterCounter {

    /*=============================================
    ===== Challenge 4.3 - File Letter Counter =====
    ===============================================

    We told you this one wasn't going to be great either. After this, it's back to space, though.
    Our boss wants to be able to access astronaut names from individual files. You don't need to
    worry about creating those files or anything for right now. He already has them, but he wants
    to be able to open them using your software. Opening files will come in handy later.

    Anyway. Please write a program that asks the user to enter the name of a file, and then asks
    the user to enter a character. The program should count and display the numbero f times that 
    the letter appears in the file. The files are already provided and are named "Astronaut[x].txt."

    You can recycle a lot of code from the last assignment. This type of change to add functionality
    to an old piece of software is referred to as "iterative design", and it is how the software 
    industry works. Everyone is iterating everything all the time.


    Things you need to pass the tests:
    Input 1 - "Please enter the name of the file."
    Input 2 - "Enter a letter that you want counted."
    Output 1 - "The letter [letter] appears [number] times in that file."
    Error output - Should display the actual error message generated by Java.
    
    File input stuff on pg 230 in textbook

     */

    public static void main(String[] args) throws FileNotFoundException, java.io.IOException {
        // Variables for filename, output, input, letter, and count
        // Keyboard Scanner
        try {
            // Get the file name and letter to count from the user.
            // Close the keyboard

            // Make sure the letter is uppercase.

            // Retrieve the letter.

            // Open the file.

            // Read the first line from the file.

            // Process the entire file.
                // Get the uppercase equivalent of the line.

                // Count the number of times the letter appears
                // in the line.

                // Read the next line.

            // Close the file.

            // Format and display the count.

            // Close the application
            String choosenLetter;
            String fileChoice;
            int number = 0;
            String astronautsNameDown;
            String astronautsName;
            int nameLength = 0;
            char current;
            char compare;
            int position = 0;
    
            
    
            
            Scanner keyboard = new Scanner(System.in);
            
            System.out.println("Please enter the name of the file.");
            
            fileChoice = keyboard.nextLine();
            File name = new File(fileChoice);
            Scanner getname = new Scanner(name);
            astronautsName = getname.nextLine();

            System.out.println("Enter a letter that you want counted.");
            choosenLetter = keyboard.nextLine();
            
            astronautsNameDown = astronautsName.toLowerCase();
            nameLength = astronautsNameDown.length();
    
            
            choosenLetter = choosenLetter.toLowerCase();
            
            
    
           
            while (nameLength > 0 )
            {
                current = astronautsNameDown.charAt(position);
                compare = choosenLetter.charAt(0);
                if (compare == current)
                    {
                        number++;
                    }
                position++;
                nameLength--;
                
            }
            choosenLetter = choosenLetter.toUpperCase();
    
            
            System.out.println("The letter " + choosenLetter + " appears " + number +" times in that file." );
        }
        catch (FileNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException e) {
            System.out.println(e);
        }
    }
}
